name = "arte-fogao"
main = "src/worker.js"
compatibility_date = "2026-08-28"

[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "arte-fogao-db"
database_id = "3c348acf-de13-4989-be17-14ad4a8bef4d"
